import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "High OG Electro Orange (GS)",
    discountedPrice: "9600",
    originalPrice: "11000",
    discount: "12.7",
    image: "AssetPublic/Images/High OG Electro Orange (GS).webp",
    inWishlist: false,
    rating: "5",
    categoryName: "air-jordan",
  },
  {
    _id: uuid(),
    title: "High OG SP Fragment x Travis Scott",
    discountedPrice: "248220",
    originalPrice: "275,800",
    discount: "10",
    image: "AssetPublic/Images/High OG SP Fragment x Travis Scott.webp",
    inWishlist: false,
    rating: "4",
    categoryName: "air-jordan",
  },
  {
    _id: uuid(),
    title: "High Switch Peach",
    discountedPrice: "11340",
    originalPrice: "12400",
    discount: "5",
    image: "AssetPublic/Images/HIGH SWITCH PEACH.webp",
    inWishlist: false,
    rating: "5",
    categoryName: "air-jordan",
  },
  {
    _id: uuid(),
    title: "High Zoom Air CMFT Olive Aura (W)",

    discountedPrice: "10560",
    originalPrice: "11000",
    discount: "2",
    image: "AssetPublic/Images/High Zoom Air CMFT Olive Aura (W).webp",
    inWishlist: false,
    rating: "4",
    categoryName: "air-jordan",
  },
  {
    _id: uuid(),
    title: "High Zoom Air CMFT PSG Paris Saint-Germain",
    discountedPrice: "17880",
    originalPrice: "22350",
    discount: "25",
    image: "AssetPublic/Images/High Zoom Air CMFT PSG Paris Saint-Germain.webp",
    inWishlist: false,
    rating: "5",
    categoryName: "air-jordan",
  },
  {
    _id: uuid(),
    title: "High Zoom Air CMFT Sail (W)",
    discountedPrice: "11340",
    originalPrice: "12400",
    discount: "4",
    image: "AssetPublic/Images/High Zoom Air CMFT Sail (W).webp",
    inWishlist: false,
    rating: "3",
    categoryName: "air-jordan",
  },
  {
    _id: uuid(),
    title: "HIGH ZOOM AIR CMFT STADIUM GREEN",
    discountedPrice: "8100",
    originalPrice: "9040",
    discount: "8",
    image: "AssetPublic/Images/HIGH ZOOM AIR CMFT STADIUM GREEN.webp",
    inWishlist: false,
    rating: "5",
    categoryName: "air-jordan",
  },
  {
    _id: uuid(),
    title: "LOW EXPERIMENTAL HALLOWEEN",
    discountedPrice: "10680",
    originalPrice: "14000",
    discount: "14",
    image: "AssetPublic/Images/LOW EXPERIMENTAL HALLOWEEN.webp",
    inWishlist: false,
    rating: "4",
    categoryName: "nike",
  },
  {
    _id: uuid(),
    title: "LOW '07 PRM HALLOWEEN (2021)",
    discountedPrice: "7800",
    originalPrice: "8200",
    discount: "3",
    image: "AssetPublic/Images/LOW '07 PRM HALLOWEEN (2021).webp",
    inWishlist: false,
    rating: "2",
    categoryName: "nike",
  },
  {
    _id: uuid(),
    title: "not available",
    discountedPrice: "100",
    originalPrice: "",
    discount: "",
    image: "AssetPublic/Images/High OG SP Fragment x Travis Scott.webp",
    inWishlist: false,
    rating: "1",
    categoryName: "addidas",
  },
];
